import { motion } from "framer-motion";
import { BookMarked, Download } from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { KeyTerm } from "@/types/studyPack";
import { ExplainButton } from "./ExplainButton";
import { Button } from "@/components/ui/button";

interface KeyTermsSectionProps {
  terms: KeyTerm[];
}

// Download key terms as text file
const downloadKeyTerms = (keyTerms: KeyTerm[]) => {
  let content = `KEY TERMS\n${'='.repeat(50)}\n\n`;
  
  keyTerms.forEach((term, index) => {
    content += `${index + 1}. ${term.term}\n`;
    content += `   Meaning: ${term.meaning}\n`;
    if (term.example) {
      content += `   Example: ${term.example}\n`;
    }
    content += '\n';
  });
  
  content += `${'='.repeat(50)}\nTotal Terms: ${keyTerms.length}\nGenerated by NotePilot\n`;
  
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `key-terms-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const KeyTermsSection = ({ terms }: KeyTermsSectionProps) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="border-border shadow-md">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-lg font-display">
              <BookMarked className="w-5 h-5 text-primary" />
              Key Terms ({terms.length})
            </CardTitle>
            <Button
              onClick={() => downloadKeyTerms(terms)}
              variant="outline"
              size="sm"
              className="gap-2"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download</span>
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="space-y-2">
            {terms.map((term, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.03 }}
              >
                <AccordionItem
                  value={`term-${index}`}
                  className="border border-border rounded-lg px-4 data-[state=open]:bg-secondary/50"
                >
                  <AccordionTrigger className="hover:no-underline py-3">
                    <div className="flex items-center gap-2 flex-1">
                      <span className="font-semibold text-foreground">{term.term}</span>
                      <ExplainButton
                        content={`${term.term}: ${term.meaning}`}
                        type="key term"
                      />
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <div className="space-y-2">
                      <p className="text-foreground">{term.meaning}</p>
                      {term.example && (
                        <p className="text-sm text-muted-foreground italic border-l-2 border-accent pl-3">
                          Example: {term.example}
                        </p>
                      )}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </motion.div>
            ))}
          </Accordion>
        </CardContent>
      </Card>
    </motion.div>
  );
};
